#!/usr/bin/env python3
import importlib.util, sys, os
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
spec = importlib.util.spec_from_file_location("gen", "scripts/generate.py")
gen = importlib.util.module_from_spec(spec); spec.loader.exec_module(gen)

DEF_GEAR = [
    ("12-inch Cast Iron Skillet", "Sears and holds heat."),
    ("Instant-Read Thermometer", "Stop guessing on doneness."),
    ("Silicone-Tipped Tongs", "Flip without scratching."),
]

RECIPES = [
  {
    "slug": "classic-smashburgers", "title": "Classic Smashburgers",
    "description": "Thin, crispy-edged burgers with a deep sear. Done in 10 minutes flat.",
    "category": "Beef", "subcategory": "Ground Beef",
    "sections": ["Budget Meals"], "budgetFilters": ["Ground & Cheap", "$5–$10 Meals"],
    "prepTime": 5, "cookTime": 8, "servings": 4, "macros": [620, 38, 33, 38],
    "ingredients": [
      (1, "lb", "ground beef (80/20)"), (4, "", "burger buns"), (4, "slices", "American cheese"),
      (1, "tsp", "salt"), (0.5, "tsp", "black pepper"), (1, "tbsp", "neutral oil"),
      (None, "", "pickles, onion, sauce to serve"),
    ],
    "instructions": [
      "Roll the beef into 4 loose balls. Don't pack them tight.",
      "Get a cast iron skillet screaming hot over high heat. Add the oil.",
      "Drop a ball in and smash it flat with a spatula. Press hard for 10 seconds. Salt and pepper the top.",
      "Cook 2 minutes until the edges are dark and crispy. Flip.",
      "Add cheese, cook 1 more minute. Stack on a bun with your toppings. Eat immediately.",
    ],
    "isBudget": True, "costPerServing": 2.10,
    "costBreakdown": [("Ground beef 1 lb", 5.00), ("Buns 4-pack", 2.00), ("Cheese 4 slices", 1.40)],
    "gear": [("12-inch Cast Iron Skillet", "The crispy edges need cast iron."), ("Sturdy Metal Spatula", "For the smash.")],
    "pubDate": "2025-05-20", "featured": True,
  },
  {
    "slug": "pan-seared-ribeye", "title": "Pan-Seared Ribeye",
    "description": "Steakhouse ribeye on the stove. Crusty outside, pink inside, butter-basted.",
    "category": "Beef", "subcategory": "Steaks & Grills",
    "sections": ["Low Carb"], "budgetFilters": [],
    "prepTime": 5, "cookTime": 10, "servings": 2, "macros": [710, 52, 1, 56],
    "ingredients": [
      (1, "", "ribeye steak (about 1 lb, 1.5-inch thick)"), (1, "tbsp", "neutral oil"),
      (2, "tbsp", "butter"), (3, "cloves", "garlic, smashed"), (1, "tsp", "salt"), (0.5, "tsp", "pepper"),
    ],
    "instructions": [
      "Take the steak out of the fridge 30 minutes early. Pat it bone dry. Salt and pepper both sides.",
      "Heat oil in a cast iron skillet until it just smokes.",
      "Lay the steak down. Don't move it for 3 minutes. Flip and sear the other side 2 minutes.",
      "Add butter and garlic. Tilt the pan and spoon the butter over the steak for 1 minute.",
      "Pull at 130°F for medium-rare. Rest 5 minutes before slicing. Always rest it.",
    ],
    "isBudget": False, "costPerServing": None, "costBreakdown": [],
    "gear": [("12-inch Cast Iron Skillet", "Only thing that gets hot enough."), ("Instant-Read Thermometer", "130°F = medium-rare.")],
    "pubDate": "2025-05-18", "featured": True,
  },
  {
    "slug": "slow-cooker-beef-chili", "title": "Slow Cooker Beef Chili",
    "description": "Dump everything in before work. Come home to a pot of chili that fed you for days.",
    "category": "Beef", "subcategory": "Slow Cooker / One-Pot",
    "sections": ["Budget Meals", "Meal Prep"], "budgetFilters": ["Big Batch", "Soups & Fillers"],
    "prepTime": 10, "cookTime": 360, "servings": 6, "macros": [430, 32, 34, 18],
    "ingredients": [
      (1, "lb", "ground beef"), (2, "cans", "kidney beans, drained"), (1, "can", "diced tomatoes"),
      (1, "can", "tomato sauce"), (1, "", "onion, chopped"), (2, "tbsp", "chili powder"),
      (1, "tbsp", "cumin"), (1, "tsp", "salt"),
    ],
    "instructions": [
      "Brown the ground beef and onion in a pan for 5 minutes. Drain the grease.",
      "Dump the beef, beans, tomatoes, tomato sauce, and spices into the slow cooker. Stir.",
      "Cover and cook on LOW for 6 hours (or HIGH for 3).",
      "Taste and add more salt or chili powder if it needs it. Serve with cheese on top.",
    ],
    "isBudget": True, "costPerServing": 1.85,
    "costBreakdown": [("Ground beef 1 lb", 5.00), ("Beans 2 cans", 1.80), ("Tomatoes + sauce", 2.00), ("Onion + spices", 2.30)],
    "gear": [("6-Quart Slow Cooker", "Set it and forget it."), ("Wooden Spoon", "For stirring and serving.")],
    "pubDate": "2025-05-16",
  },
  {
    "slug": "sunday-pot-roast", "title": "Sunday Pot Roast",
    "description": "Fall-apart beef and vegetables in one pot. Looks impressive, takes 15 minutes of work.",
    "category": "Beef", "subcategory": "Roasts",
    "sections": [], "budgetFilters": [],
    "prepTime": 15, "cookTime": 240, "servings": 6, "macros": [540, 45, 28, 26],
    "ingredients": [
      (3, "lb", "chuck roast"), (4, "", "carrots, chunked"), (3, "", "potatoes, quartered"),
      (1, "", "onion, quartered"), (2, "cups", "beef broth"), (2, "tbsp", "oil"),
      (1, "tbsp", "salt"), (1, "tsp", "pepper"),
    ],
    "instructions": [
      "Pat the roast dry and salt it all over. Heat oil in a heavy pot.",
      "Sear the roast 3 minutes per side until brown. This is where the flavor comes from.",
      "Add the broth, onion, carrots, and potatoes around the roast.",
      "Cover and cook in a 300°F oven for 4 hours, until it shreds with a fork.",
      "Pull it out, let it rest 10 minutes, then break it apart and serve with the veggies.",
    ],
    "isBudget": False, "costPerServing": None, "costBreakdown": [],
    "gear": [("Heavy Dutch Oven or Oven-Safe Pot", "Goes stove to oven."), ("Instant-Read Thermometer", "Pull at 200°F for shreddable.")],
    "pubDate": "2025-05-14",
  },
  {
    "slug": "crispy-chicken-thighs", "title": "Crispy Chicken Thighs",
    "description": "Shatteringly crispy skin, juicy meat. One pan, barely any cleanup.",
    "category": "Chicken", "subcategory": "Chicken Thighs",
    "sections": ["Low Carb"], "budgetFilters": [],
    "prepTime": 5, "cookTime": 30, "servings": 4, "macros": [380, 28, 1, 29],
    "ingredients": [
      (6, "", "bone-in, skin-on chicken thighs"), (1, "tbsp", "oil"), (1, "tsp", "salt"),
      (1, "tsp", "garlic powder"), (1, "tsp", "paprika"), (0.5, "tsp", "pepper"),
    ],
    "instructions": [
      "Pat the thighs completely dry. Wet skin won't crisp.",
      "Mix the salt, garlic powder, paprika, and pepper. Rub it all over.",
      "Heat oil in an oven-safe skillet. Lay thighs skin-side down. Cook 8 minutes without touching.",
      "Flip them, then slide the pan into a 425°F oven for 20 minutes.",
      "Check for 175°F at the thickest part. Rest 5 minutes and serve.",
    ],
    "isBudget": False, "costPerServing": None, "costBreakdown": [],
    "gear": [("Oven-Safe Cast Iron Skillet", "Stove to oven in one pan."), ("Instant-Read Thermometer", "175°F for thighs.")],
    "pubDate": "2025-05-22", "featured": True,
  },
  {
    "slug": "juicy-baked-chicken-breast", "title": "Juicy Baked Chicken Breast",
    "description": "The fix for dry chicken. Five lunches done in half an hour.",
    "category": "Chicken", "subcategory": "Chicken Breasts",
    "sections": ["Meal Prep"], "budgetFilters": [],
    "prepTime": 5, "cookTime": 22, "servings": 4, "macros": [260, 44, 2, 8],
    "ingredients": [
      (4, "", "chicken breasts"), (1, "tbsp", "oil"), (1, "tsp", "salt"),
      (1, "tsp", "garlic powder"), (1, "tsp", "paprika"), (0.5, "tsp", "pepper"),
    ],
    "instructions": [
      "Heat the oven to 425°F. Pat the breasts dry.",
      "Rub with oil, then coat with the salt, garlic powder, paprika, and pepper.",
      "Lay on a lined sheet pan. Bake 20–22 minutes until they hit 165°F.",
      "Rest 5 minutes before cutting or all the juice runs out. Slice for meal prep boxes.",
    ],
    "isBudget": False, "costPerServing": None, "costBreakdown": [],
    "gear": [("Heavy Sheet Pan", "Even cooking, easy cleanup."), ("Glass Meal Prep Containers", "Portion for the week.")],
    "pubDate": "2025-05-19",
  },
  {
    "slug": "sticky-bbq-wings", "title": "Sticky BBQ Wings",
    "description": "Oven-baked wings that come out crispy, then tossed in sticky sauce. No fryer needed.",
    "category": "Chicken", "subcategory": "Wings & Drumsticks",
    "sections": [], "budgetFilters": [],
    "prepTime": 10, "cookTime": 45, "servings": 4, "macros": [480, 34, 18, 30],
    "ingredients": [
      (2, "lb", "chicken wings"), (1, "tbsp", "baking powder"), (1, "tsp", "salt"),
      (1, "tsp", "garlic powder"), (0.75, "cup", "BBQ sauce"),
    ],
    "instructions": [
      "Pat wings very dry. Toss with baking powder, salt, and garlic powder — the baking powder is the crispy trick.",
      "Lay on a rack over a sheet pan so air gets underneath.",
      "Bake at 425°F for 45 minutes, flipping halfway, until golden and crispy.",
      "Toss the hot wings in BBQ sauce and serve right away.",
    ],
    "isBudget": False, "costPerServing": None, "costBreakdown": [],
    "gear": [("Wire Rack + Sheet Pan", "Air under the wings = crispy."), ("Mixing Bowl Set", "For tossing in sauce.")],
    "pubDate": "2025-05-12",
  },
  {
    "slug": "garlic-butter-pork-chops", "title": "Garlic Butter Pork Chops",
    "description": "Thick chops seared and basted in garlic butter. On the table in 15 minutes.",
    "category": "Pork", "subcategory": "Pork Chops",
    "sections": ["Low Carb"], "budgetFilters": [],
    "prepTime": 5, "cookTime": 10, "servings": 2, "macros": [430, 40, 2, 28],
    "ingredients": [
      (2, "", "thick-cut pork chops"), (2, "tbsp", "butter"), (3, "cloves", "garlic, smashed"),
      (1, "tbsp", "oil"), (1, "tsp", "salt"), (0.5, "tsp", "pepper"),
    ],
    "instructions": [
      "Pat chops dry, season both sides with salt and pepper.",
      "Heat oil in a skillet over medium-high. Sear chops 4 minutes without moving them.",
      "Flip, add butter and garlic, and spoon the butter over the chops for 3–4 minutes.",
      "Pull at 145°F. Rest 5 minutes — pork should still be slightly pink and juicy.",
    ],
    "isBudget": False, "costPerServing": None, "costBreakdown": [],
    "gear": [("12-inch Cast Iron Skillet", "Best sear."), ("Instant-Read Thermometer", "145°F, not 160°F.")],
    "pubDate": "2025-05-11",
  },
  {
    "slug": "slow-cooker-pulled-pork", "title": "Slow Cooker Pulled Pork",
    "description": "Four ingredients, eight hours, a mountain of pulled pork. Cheapest meat-per-dollar there is.",
    "category": "Pork", "subcategory": "Pork Shoulder & Roasts",
    "sections": ["Meal Prep", "Budget Meals"], "budgetFilters": ["Big Batch", "$5–$10 Meals"],
    "prepTime": 10, "cookTime": 480, "servings": 8, "macros": [390, 36, 12, 22],
    "ingredients": [
      (4, "lb", "pork shoulder"), (1, "tbsp", "salt"), (1, "tbsp", "brown sugar"),
      (1, "tbsp", "paprika"), (1, "cup", "BBQ sauce"), (8, "", "buns to serve"),
    ],
    "instructions": [
      "Mix salt, brown sugar, and paprika. Rub it all over the pork shoulder.",
      "Put it in the slow cooker, fat side up. No liquid needed — it makes its own.",
      "Cover and cook on LOW for 8 hours, until it falls apart when poked.",
      "Pull the pork apart with two forks. Drain most of the liquid, then mix in BBQ sauce.",
      "Pile onto buns. Freeze the rest in portions for easy future meals.",
    ],
    "isBudget": True, "costPerServing": 1.75,
    "costBreakdown": [("Pork shoulder 4 lb", 8.00), ("BBQ sauce", 2.50), ("Buns 8-pack", 3.50)],
    "gear": [("6-Quart Slow Cooker", "Big enough for the shoulder."), ("Freezer Storage Bags", "Portion the leftovers.")],
    "pubDate": "2025-05-10",
  },
  {
    "slug": "crispy-skin-salmon", "title": "Crispy-Skin Salmon",
    "description": "Restaurant-crispy salmon skin in one pan. Ten minutes, four ingredients.",
    "category": "Fish", "subcategory": "Salmon",
    "sections": ["Low Carb"], "budgetFilters": [],
    "prepTime": 5, "cookTime": 8, "servings": 2, "macros": [410, 40, 0, 27],
    "ingredients": [
      (2, "", "salmon fillets, skin on"), (1, "tbsp", "oil"), (1, "tsp", "salt"),
      (0.5, "tsp", "pepper"), (1, "", "lemon, to serve"),
    ],
    "instructions": [
      "Pat the salmon very dry, especially the skin. Season both sides.",
      "Heat oil in a non-stick or cast iron pan over medium-high.",
      "Lay the fillets skin-side down and press flat for 10 seconds. Cook 5 minutes without moving.",
      "Flip and cook 2–3 minutes more. The skin should be shatter-crispy.",
      "Squeeze lemon over the top and serve.",
    ],
    "isBudget": False, "costPerServing": None, "costBreakdown": [],
    "gear": [("Fish Spatula", "Thin enough to get under the skin."), ("Non-Stick Frying Pan", "Skin won't stick.")],
    "pubDate": "2025-05-24", "featured": True,
  },
  {
    "slug": "garlic-butter-shrimp", "title": "Garlic Butter Shrimp Skillet",
    "description": "Frozen bag to dinner in under 10 minutes. Garlicky, buttery, done.",
    "category": "Fish", "subcategory": "Shrimp",
    "sections": ["Low Carb"], "budgetFilters": [],
    "prepTime": 5, "cookTime": 6, "servings": 2, "macros": [290, 34, 3, 15],
    "ingredients": [
      (1, "lb", "shrimp, peeled (thawed if frozen)"), (3, "tbsp", "butter"), (4, "cloves", "garlic, minced"),
      (1, "tsp", "salt"), (0.5, "tsp", "red pepper flakes"), (1, "", "lemon"),
    ],
    "instructions": [
      "Pat the shrimp dry and season with salt.",
      "Melt butter in a skillet over medium heat. Add garlic and pepper flakes, cook 30 seconds.",
      "Add the shrimp in one layer. Cook 2 minutes per side until pink and curled.",
      "Squeeze lemon over the top, toss, and serve. Don't overcook — shrimp get rubbery fast.",
    ],
    "isBudget": False, "costPerServing": None, "costBreakdown": [],
    "gear": [("12-inch Cast Iron Skillet", "Even heat."), ("Silicone-Tipped Tongs", "Quick flipping.")],
    "pubDate": "2025-05-21",
  },
  {
    "slug": "tuna-melt", "title": "Diner-Style Tuna Melt",
    "description": "Canned tuna, bread, cheese. A hot, cheesy meal for a couple bucks.",
    "category": "Fish", "subcategory": "Canned & Easy",
    "sections": ["Budget Meals"], "budgetFilters": ["Pantry Staples", "$5–$10 Meals"],
    "prepTime": 5, "cookTime": 6, "servings": 2, "macros": [520, 33, 34, 27],
    "ingredients": [
      (2, "cans", "tuna, drained"), (3, "tbsp", "mayo"), (4, "slices", "bread"),
      (4, "slices", "cheddar cheese"), (2, "tbsp", "butter"), (0.5, "tsp", "salt"),
    ],
    "instructions": [
      "Mix the tuna, mayo, and salt in a bowl.",
      "Butter one side of each bread slice. Build sandwiches butter-side out, with cheese and tuna inside.",
      "Cook in a skillet over medium for 3 minutes per side, pressing down, until golden and the cheese melts.",
      "Cut in half and eat while it's hot.",
    ],
    "isBudget": True, "costPerServing": 1.95,
    "costBreakdown": [("Tuna 2 cans", 2.40), ("Bread", 1.00), ("Cheese", 1.40), ("Mayo + butter", 1.10)],
    "gear": [("Non-Stick Frying Pan", "Even grilling."), ("Fish Spatula", "Clean flip.")],
    "pubDate": "2025-05-08",
  },
  {
    "slug": "egg-fried-rice", "title": "10-Minute Egg Fried Rice",
    "description": "Leftover rice, a few eggs, and whatever's in the fridge. Cheapest fast food there is.",
    "category": "Budget Meals", "subcategory": "Pantry Staples",
    "sections": [], "budgetFilters": ["Pantry Staples", "$5–$10 Meals", "Ground & Cheap"],
    "prepTime": 5, "cookTime": 8, "servings": 3, "macros": [340, 12, 48, 11],
    "ingredients": [
      (3, "cups", "cooked rice (day-old is best)"), (3, "", "eggs, beaten"), (2, "tbsp", "soy sauce"),
      (2, "tbsp", "oil"), (1, "cup", "frozen peas and carrots"), (2, "", "green onions, sliced"),
    ],
    "instructions": [
      "Heat oil in a large pan or wok over high heat. Pour in the eggs and scramble fast, then push to the side.",
      "Add the frozen veggies and cook 2 minutes.",
      "Add the rice, breaking up any clumps. Stir-fry 3 minutes until hot.",
      "Pour in soy sauce, toss everything together, top with green onions, and serve.",
    ],
    "isBudget": True, "costPerServing": 1.20,
    "costBreakdown": [("Rice", 0.80), ("Eggs 3", 0.90), ("Frozen veg", 1.00), ("Soy + onion", 0.90)],
    "gear": [("Large Non-Stick Pan or Wok", "High heat, lots of room."), ("Wooden Spoon", "For tossing.")],
    "pubDate": "2025-05-26", "featured": True,
  },
  {
    "slug": "sheet-pan-chicken-veggies", "title": "Sheet Pan Chicken & Veggies",
    "description": "Everything on one tray, into the oven, done. Five meal-prep boxes from one pan.",
    "category": "Meal Prep", "subcategory": "Sheet Pan Meals",
    "sections": ["Low Carb"], "budgetFilters": [],
    "prepTime": 10, "cookTime": 25, "servings": 4, "macros": [330, 38, 14, 13],
    "ingredients": [
      (1.5, "lb", "chicken thighs, boneless"), (1, "", "broccoli head, chopped"),
      (2, "", "bell peppers, sliced"), (2, "tbsp", "oil"), (1, "tsp", "salt"),
      (1, "tsp", "garlic powder"), (1, "tsp", "paprika"),
    ],
    "instructions": [
      "Heat the oven to 425°F. Chop the chicken and veggies into similar-sized pieces.",
      "Spread everything on a sheet pan. Drizzle with oil and toss with salt, garlic powder, and paprika.",
      "Spread it into a single layer so it roasts instead of steams.",
      "Roast 25 minutes, stirring once, until the chicken hits 165°F and the edges char.",
      "Divide into containers for the week.",
    ],
    "isBudget": False, "costPerServing": None, "costBreakdown": [],
    "gear": [("Heavy Sheet Pan", "The whole meal cooks on it."), ("Glass Meal Prep Containers", "Five lunches sorted.")],
    "pubDate": "2025-05-25",
  },
]

for r in RECIPES:
    if not r.get("gear"):
        r["gear"] = DEF_GEAR
    gen.write_recipe(r)
    gen.write_svg(r)

print(f"Wrote {len(RECIPES)} recipes + images.")
